global using System.Globalization;
global using System.Net.Http.Headers;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using NAudio.CoreAudioApi;
global using NAudio.Wave;
global using OpenCvSharp;
